### ISSUE TITLE
HTTP 429 error with virustotal-subdomains.lua

### ISSUE THREAD

**Issue by yeroc-sebrof** [kpcyrd/sn0int-modules#1]
It is not clear if there is a delay option for this module, 429 errors were being responded within this module runtime

**Comment by kpcyrd** [comment]
Thanks for reporting this! I've introduced a call to `ratelimit_throttle` in the 0.1.1 update, I'm not sure how slow virustotal wants us to go, it's set to "not more than 5reqs every 15sec" right now.

**Comment by yeroc-sebrof** [comment]
Hmm, just looked through the request now. I can't see how slow they want it either since it's not their official api that this module uses. I'll close now 🙂
